// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrGpY4MoSa7L0NXHZo61DE_hfV94A76pY',
    appId: '1:148820218930:web:57ff47e447dcf0b8b0d82b',
    messagingSenderId: '148820218930',
    projectId: 'ivictim-61de3',
    authDomain: 'ivictim-61de3.firebaseapp.com',
    storageBucket: 'ivictim-61de3.appspot.com',
    measurementId: 'G-1CRMMDRBG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFdYBvvdraqKN47_QpvtXNiWlEexN-CIc',
    appId: '1:148820218930:android:5512c9bcaa8ee4d8b0d82b',
    messagingSenderId: '148820218930',
    projectId: 'ivictim-61de3',
    storageBucket: 'ivictim-61de3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMcpy6HoQR3XcnDoMQiM61Q5QRb039EaU',
    appId: '1:148820218930:ios:5bae870b8f89bac9b0d82b',
    messagingSenderId: '148820218930',
    projectId: 'ivictim-61de3',
    storageBucket: 'ivictim-61de3.appspot.com',
    iosClientId: '148820218930-n3u4nb7viqhqsfjj4ios02datfer72s9.apps.googleusercontent.com',
    iosBundleId: 'com.ivictim.ivictim',
  );
}
